### ISSUE TITLE
Работа

### ISSUE THREAD

**Issue by ValeraBro** [xai-org/grok#10]
Илон Маск, возьми на работу пожалуйста )))

Если надо будет,дообучаюсь. Готов контракт подписать лет на 20 хоть, что после обучения останусь)

Сфера айти, пишу код на с#. Могу другой язык выучить. Матем есть, физика есть)

Пиши :)

**Comment by jxnkie** [comment]
ебануться, он же русскй сразу поймёт
да и с такими приколами меня тоже на работу возьмите, я питонист
100 рублей скрипт 200 рублей бот

**Comment by NeuroDonu** [comment]
Питон выучи

**Comment by iamwavecut** [comment]
Ну раз пошла така пьянка: 

Меня тоже зовут Валера и я могу писать код. Да. Какой угодно. Если Илон даст зарплату хорошую могу хоть танцевать на шесте!

 https://linkedin.com/in/wavecut/en доьавляйтесь!

**Comment by iGroza** [comment]
🧬4️⃣2️⃣

**Comment by jxnkie** [comment]
> 🧬4️⃣2️⃣

42 БРАТУХАА

**Comment by ValeraBro** [comment]
> Ну раз пошла така пьянка: 
> 
> Меня тоже зовут Валера и я могу писать код. Да. Какой угодно. Если Илон даст зарплату хорошую могу хоть танцевать на шесте!
> 
>  https://linkedin.com/in/wavecut/en доьавляйтесь! 

Момент. Я не только пишу код,а ещё знаю физику и матан. Если Илон возьмёт к себе,я любой яп выучу,что надо будет))

А ТАКЖЕ ЦЕЛЕУСТРЕМЛЕННОСТЬ, МОГУ УБИТЬ ХОТЬ 24/7 ВРЕМЕНИ НА РАБОТУ

**Comment by Volodya132** [comment]
> ебануться, он же русский сразу поймёт
> да и с такими приколами меня тоже на работу возьмите, я питонист
> 100 рублей скрипт 200 рублей бот

Ми, пітоністи, гордий народ...

**Comment by jxnkie** [comment]
> > ебануться, он же русский сразу поймёт
> > да и с такими приколами меня тоже на работу возьмите, я питонист
> > 100 рублей скрипт 200 рублей бот
> 
> Ми, пітоністи, гордий народ...

![image](https://github.com/xai-org/grok/assets/162614821/7ff91617-c11e-49da-89b0-bc7ae8b23c55)

**Comment by itbeard** [comment]
Раз такой душевный тред, то и я впишусь. Правда не с работой, а с обращением к Игорю Бабушкину: Игорь, го в подкаст АйТиБорода (https://www.youtube.com/@itbeard) и в подкаст про новости ИИ - AIA Podcast (https://www.youtube.com/@aw-club-ru). Очень тебя ждем и там и там :)

**Comment by jxnkie** [comment]
> Раз такой душевный тред, то и я впишусь. Правда не с работой, а с обращением к Игорю Бабушкину: Игорь, го в подкаст АйТиБорода (https://www.youtube.com/@itbeard) и в подкаст про новости ИИ - AIA Podcast (https://www.youtube.com/@aw-club-ru). Очень тебя ждем и там и там :)

сабнулся

**Comment by ValeraBro** [comment]
> Раз такой душевный тред, то и я впишусь. Правда не с работой, а с обращением к Игорю Бабушкину: Игорь, го в подкаст АйТиБорода (https://www.youtube.com/@itbeard) и в подкаст про новости ИИ - AIA Podcast (https://www.youtube.com/@aw-club-ru). Очень тебя ждем и там и там :)

Без пиара в комментах! Лучше подпишись на гитхаб

**Comment by iamwavecut** [comment]
Сабнулся, когда это еще не было мейнстримом

**Comment by gerasim13** [comment]
Мне вообще пох на стэк! Все знаю, все могу.

**Comment by Vtmpas** [comment]
я тоже хочу. жду оффер

**Comment by iamwavecut** [comment]
> Без пиара в комментах! Лучше подпишись на гитхаб ))

не, мы так не договаривались

**Comment by flexorx** [comment]
Дайте два.

**Comment by StasDachinsky** [comment]
Илон возьми в штат(ы)! Пишу на расте и тайпскрипте

**Comment by DaLLuZZ** [comment]
![1705571278](https://github.com/xai-org/grok/assets/79600653/09b32d5b-64b5-4b41-a3d3-f6cc4800959e)

**Comment by weirdgiraffe** [comment]
То есть взяли тебя, @ValeraBro ?

**Comment by ValeraBro** [comment]
> То есть взяли тебя, @ValeraBro ?

Нет, просто закрыли это обсуждение :(
Илон Маск теперь не увидит просьбу (

**Comment by flexorx** [comment]
@weirdgiraffe @ValeraBro Дообучать будут, как человека, в Neuralink.

**Comment by DmitryIo** [comment]
Валера сколько жмешь?

**Comment by fatezi404** [comment]
пишу на паскале, готов мыть унитазы на одном из этажей пентхауса Маска

**Comment by flexorx** [comment]
Валерий, от "валео" - значит "быть сильным и здоровым"

**Comment by ValeraBro** [comment]
> Валера сколько жмешь?

Х+15, где х- мой вес

**Comment by weirdgiraffe** [comment]
@ValeraBro  А, просто closed as completed сбило с толку. Если ь брутального закрыли с won't fix, вопросов бы не было 😀

**Comment by iamwavecut** [comment]
Возможно, это "закрыто как конченный"

**Comment by jxnkie** [comment]
> Возможно, это "закрыто как конченный"

возможно

**Comment by Germandev55** [comment]
пишу код на chatGPT. Илон Маск, подпишись: https://t.me/junkyardmathml

**Comment by flexorx** [comment]
> Возможно, это "закрыто как конченный"

возможно

**Comment by Artem-Verenko** [comment]
Уважаемый Илон Маск!
Пишу Вам с замиранием сердца, ибо судьба человечества (а может быть, и всей галактики!) повисла на волоске! Да-да, именно так!
Я, Артем (не Валера), скромный программист на C#, с пылкой страстью к покорению космоса, искусственному интеллекту и прочим футуристическим штучкам, готов бросить все к Вашим ногам!
Почему именно я?
• Мозг - компьютер последнего поколения: умею писать код на C#, а при необходимости освою и другие языки программирования. Математика и физика - мои верные друзья.
• Готовность к самосовершенствованию: жажду грызть гранит науки и обучаться 24/7, лишь бы только попасть в Вашу команду гениев!
• Энтузиазм зашкаливает: готов(а) подписать контракт хоть на 20 лет, лишь бы творить вместе с Вами будущее!
Где меня найти:
• Мой профиль LinkedIn: https://www.linkedin.com/in/artemverenko/
• (А если вдруг захотите лично убедиться в моем потенциале, пишите, я примчусь с энтузиазмом!)
P.S.
• Прилагаю резюме, но поверьте, мой энтузиазм и рвение к работе в SpaceX/Tesla/Boring Company/Neuralink (нужное подчеркнуть) в сотни раз превосходят эти жалкие бумажки!
• И да, юмор у меня тоже имеется. ;)
С уважением и благоговением,
Артем.
P.P.S.
• Прошу прощения за дерзость, но будущее зовет! ;)

**Comment by ValeraBro** [comment]
И нафуя ты чат гпт использовал)))
Мое смс переформулировал, я тоже так делал сейчас,но палевно

**Comment by ValeraBro** [comment]
> Уважаемый Илон Маск!
> Пишу Вам с замиранием сердца, ибо судьба человечества (а может быть, и всей галактики!) повисла на волоске! Да-да, именно так!
> Я, Артем (не Валера), скромный программист на C#, с пылкой страстью к покорению космоса, искусственному интеллекту и прочим футуристическим штучкам, готов бросить все к Вашим ногам!
> Почему именно я?
> • Мозг - компьютер последнего поколения: умею писать код на C#, а при необходимости освою и другие языки программирования. Математика и физика - мои верные друзья.
> • Готовность к самосовершенствованию: жажду грызть гранит науки и обучаться 24/7, лишь бы только попасть в Вашу команду гениев!
> • Энтузиазм зашкаливает: готов подписать контракт хоть на 20 лет, лишь бы творить вместе с Вами будущее!
> Где меня найти:
> • Мой профиль LinkedIn: https://www.linkedin.com/in/artemverenko/
> • (А если вдруг захотите лично убедиться в моем потенциале, пишите, я примчусь с энтузиазмом!)
> P.S.
> • Прилагаю резюме, но поверьте, мой энтузиазм и рвение к работе в SpaceX/Tesla/Boring Company/Neuralink (нужное подчеркнуть) в сотни раз превосходят эти жалкие бумажки!
> • И да, юмор у меня тоже имеется. ;)
> С уважением и благоговением,
> Артем.
> P.P.S.
> • Прошу прощения за дерзость, но будущее зовет! ;)
> 

А,ну ты схитрил. Переформулировал через нейронку и вставил свой линкед

**Comment by Artem-Verenko** [comment]
> И нафуя ты чат гпт использовал))) Мое смс переформулировал, я тоже так делал сейчас,но палевно

Ты не прав хотя бы потому, что я использовал gemini

**Comment by gerasim13** [comment]
Илон, возьми меня на работу, я не предам тебя и не буду жаловаться на то, что ты заставляешь употреблять вещества на рабочем месте.

**Comment by ValeraBro** [comment]
> 
> 
> 
> > И нафуя ты чат гпт использовал))) Мое смс переформулировал, я тоже так делал сейчас,но палевно
> 
> Ты не прав хотя бы потому, что я использовал gemini

Я ж написал,что нейронка. Все верно

**Comment by iamwavecut** [comment]
> Илон, возьми меня на работу, я не предам тебя и не буду жаловаться на то, что ты заставляешь употреблять вещества на рабочем месте.

Первый вопрос: вы прививались от COVID-19?

**Comment by gerasim13** [comment]
> > Илон, возьми меня на работу, я не предам тебя и не буду жаловаться на то, что ты заставляешь употреблять вещества на рабочем месте.
> 
> Первый вопрос: вы прививались от COVID-19?

Привит всеми вакцинами

**Comment by iamwavecut** [comment]
> > > Илон, возьми меня на работу, я не предам тебя и не буду жаловаться на то, что ты заставляешь употреблять вещества на рабочем месте.
> 
> > 
> 
> > Первый вопрос: вы прививались от COVID-19?
> 
> 
> 
> Привит всеми вакцинами

Извините, вы нам не подходите

**Comment by kstroevsky** [comment]
🇺🇦

**Comment by ValeraBro** [comment]
> 🇺🇦

Уйди лох

**Comment by iamwavecut** [comment]
> > 🇺🇦
> 
> Уйди, пожалуйста 

В вашу сторону вылетел дрон с доставкой

**Comment by ValeraBro** [comment]
> > > 🇺🇦
> > 
> > 
> > Уйди, пожалуйста
> 
> В вашу сторону вылетел дрон с доставкой

Ля, он сам пришел, прикинь

**Comment by bedbad** [comment]
If anyone's looking for a job I'm was and am looking for people to hire.
Good engineers are need as heck.
Actually any person with real work ethic and passion is dearly desired. From anywhere in the world barring security concerns.

This industry, however, has nothing to do with what you in Russian circles call "IT industry"
After maturing in America working as an engineer, mostly software engineer I never saw or heard a single person in our industry that wrote or even supported code for living called themselves that they are in "IT industry."
There are IT industry services  which is the guys who set up your offices PCs and work remote VMs so that some questionable management/employers could spy and control their employees at the workspace and even from home and IT services in the sense computer/network handyman gigs and that's it.
I don't think if you want to get a job among people who are *actually building* *actually useful* products for people you should market yourself by association with "IT industry", like "itboroda" when you'd supposedly somehow do whatever your employer says and a pole-dance and sign 25 years contracts for unspecific products/projects as it speaks volumes to your ability to be responsible for any single useful (and monetizable) product or feature. Upon checking such people haven't actually shipped a single commercial product feature in their 'career'. 
This is shame. Post-soviet enginneers used to be the best in the world (and significant, especially most hard-core engineers these days still are from there). It's people like these that make every reputation unreliable and everything a crap, these people who are not from and aren't enjoy engineering in the first place.

**Comment by iamwavecut** [comment]
Well, I def wouldn't join a team somehow led by such toxic judging perwon

**Comment by ValeraBro** [comment]
> Well, I def wouldn't join a team somehow led by such toxic judging person

Well, Elon musk is not as toxic as you think. He is as interested in the matter as I am

**Comment by iamwavecut** [comment]
> > Well, I def wouldn't join a team somehow led by such toxic judging person
> 
> Well, Elon musk is not as toxic as you think. He is as interested in the matter as I am

I was referring to the @bedbad

**Comment by ValeraBro** [comment]
Что кого, ребзя? Илон так и не написал (

**Comment by bedbad** [comment]
> > > Well, I def wouldn't join a team somehow led by such toxic judging person
> > 
> > 
> > Well, Elon musk is not as toxic as you think. He is as interested in the matter as I am
> 
> I was referring to the @bedbad
You are late 30s - 40s yo dude whose main demo website gives out backend belonging errors on the first page
and who tries to build up his resume by writing free telegram chatgpt bots

I am relieved

**Comment by ValeraBro** [comment]
> > > > Well, I def wouldn't join a team somehow led by such toxic judging person
> > > 
> > > 
> > > Well, Elon musk is not as toxic as you think. He is as interested in the matter as I am
> > 
> > I was referring to the @bedbad
> 
> You are late 30s - 40s yo dude whose main demo website gives out backend belonging errors on the first page
> and who tries to build up his resume by writing free telegram chatgpt bots
> 
> I am relieved

Чувак, насколько же мне похрен,вот честно)))
Я по-русски написал, сайт и резюме закину потом, в России всё по-другому делается,лично при встрече. Тут не смотрят гитхаб как эталон.
 Развивайся )
Я спокоен,ибо ты не знаешь даже простых вещей

**Comment by iamwavecut** [comment]
> > > > Well, I def wouldn't join a team somehow led by such toxic judging person
> > > 
> > > 
> > > Well, Elon musk is not as toxic as you think. He is as interested in the matter as I am
> > 
> > 
> > I was referring to the @bedbad
> 
> You are late 30s - 40s yo dude whose main demo website gives out backend belonging errors on the first page and who tries to build up his resume by writing free telegram chatgpt bots
> 
> I am relieved
And that's a perfect example of what I meant in my first comment about you, thanks for confirmation!
