### ISSUE TITLE
Can i run grok in gcolab?

### ISSUE THREAD

**Issue by viveke22** [xai-org/grok#2]
I tried to load this model in Google colab but it fails to load, is there any way that it will get optimized or something to load in Google colab or any other notebook like paperspace?

**Comment by j-jacobson** [comment]
What was your error message?

**Comment by RoversX** [comment]
What is the overall size of the model file?

**Comment by DoogeJ** [comment]
> What is the overall size of the model file?

Well the magnet file contains a 300GB checkpoint 🙃

**Comment by NeuroDonu** [comment]
Lol... Run grok in gcolab? Lool. Firstly, you simply don’t have enough space, even with a PRO subscription, and secondly, you don’t have enough resources to download such a model! 🤭

**Comment by ViswanathaReddyGajjala** [comment]
It may not be feasible, even with quantized variants. Wait a bit and we might be able to see those tuned quantized variants.

**Comment by RoversX** [comment]
> > What is the overall size of the model file?
> 
> Well the magnet file contains a 300GB checkpoint 🙃

Let's wait for llama3🙃

**Comment by fakerybakery** [comment]
Impossible to run in Colab. First, Colab doesn't have enough disk space to even load the model. Secondly, there isn't enough memory. Maybe llama.cpp will add support and you can run quants

**Comment by ibab** [comment]
Yeah colab is unfortunately not enough to run this model currently.
