### ISSUE TITLE
 Igor Babuschkin write me, I want to call you for an interview! 😊

### ISSUE THREAD

**Issue by itbeard** [xai-org/grok#9]
Sorry to spam you, but I don't know any other way I can reach him 🤷‍♂️
@ibab

**Comment by akshaynarisetti** [comment]
Well, he literally seems to have an email in the bio for contact

**Comment by itbeard** [comment]
> Well, he literally seems to have an email in the bio for contact

I've tried it several times, dude.

**Comment by AnikanovD** [comment]
lol kek :D

**Comment by Pingear** [comment]
It would be cool to see )

**Comment by Takeso-user** [comment]
Lex, try LinkedIn messages ))
